Prepares for deno publish
Deno publish failed with an error:

error: Relative import path "lume/core/utils/object.ts" not prefixed with / or ./ or ../ and not in import map from "file:///Users/rcogley/dev/hibana/types/lume.ts"
    at file:///Users/rcogley/dev/hibana/types/lume.ts:4:23

The error was due to how modules were being imported in types/lume.ts file. Specifically, Deno (and JSR) require that all import paths be either:

Relative paths (starting with ./, ../)
Absolute paths (starting with /)
URLs
Mapped paths (defined in an import map)

So, add an import map in a deno.json.